### ISSUE TITLE
Pasta System Traduzida

### ISSUE THREAD

**Issue by VirusY** [billarkwright/Client#2]
Oi, 
Eu tenho uma pasta "System" traduzida e funcional, pretendo disponibiliza ela para o projeto, caso, você a necessite, irei, te passo o repositório...
Link https://virus-cronus-svn.googlecode.com/svn/trunk/

Bem, Espero que o projeto prossiga firme e forte....

**Comment by billarkwright** [comment]
Agradeço. Irei adapta-la para a nova pasta System. Abraços.

**Comment by TrueVor** [comment]
Muito obrigado, virus!
Sua tradução foi de grande ajuda!
